# Configuration file for parameters

# Data directories

# Parameters for FBANK transform:

# From paper: "with a 25ms Hamming window every 10ms"
win_len: 200 # In samples. -> 25 ms
hop_len: 80 # In samples -> 10ms
len_fft: 2 ** int(np.ceil(np.log(win_len) / np.log(2.0))) # Could move out of config
#len_fft: 2*len_fft # To fill spectrum properly
sr: 8000 # Signal rate (Hz) for re-sampling:
n_mel: 128 # number of bins in log-mel spectrogram to match AST paper
norm_per_sample: True

# Choose model:
# model_name = 'conv' # Selects simple 2D conv (simple_cnn_baseline.py)
model_name: 'ASTransformer' # Any other string selects transformer: TODO, check string logic

# Transformer encoder properties
embed_dim: 768
num_heads: 8
depth: 4
n_classes: 10
dropout: 0.1
# Training loop properties
batch_size: 4  # Size 48 used in paper, with my GPU and this implementation, 4 was the sweet spot
n_epochs: 50
max_overrun: 20  # for early stopping, nb of epochs to train with no improvement in best metric
lr: 0.00001  # Learning rate used with optimiser (Adam)

# Evaluation
debug: False # debug parameter. Only set to True if issues suspected, opens various diagnostic
# plots and print statements

# Create directories if they do not exist:
